### PR TITLE
[Fix #1023] Add support for local s3 storage

### LINKED ISSUE #1023: local s3 storage
**Description**
I have a local s3 running and I want to set `--model-store` to the s3 bucket. However, I am not able to pass the credentials for my local s3. 

**TRTIS Information**
What version of TRTIS are you using?
`nvcr.io/nvidia/tensorrtserver:19.12-py3`
Are you using the TRTIS container or did you build it yourself?
I am using the TRTIS container

**To Reproduce**
1. Create the aws config folder
```
.aws/
   config
   credentials
```
config:
```
[default]
s3 =
    endpoint_url=http://minio:9000
    signature_version = s3v4

[plugins]
endpoint = awscli_plugin_endpoint
```
credentials:
```
[default]
aws_access_key_id='foo'
aws_secret_access_key='bar'
```
2. Create new image from TRTIS container by adding `awscli_plugin_endpoint` and `.aws` to the container. Dockerfile:
```
FROM nvcr.io/nvidia/tensorrtserver:19.12-py3

RUN pip3 install awscli_plugin_endpoint
COPY .aws /root/.aws
```
3. build `trtis` image from `Dockerfile
4. run server
```
docker run --rm trtis trtserver --model-store=s3://models
```

When I run TRTIS I get the following error:
```
E0113 20:41:25.707104 1 main.cc:1158] error: creating server: INTERNAL - Could not get MetaData for bucket with name models
```

**Expected behavior**
I expected it to use credentials and endpoint provided in the `.aws` folder and connect to my `s3 bucket`. What would be the proper way of using the local s3 storage? How to provide access key, secret and endpoints?

### PR DESCRIPTION
**Pull request by CoderHam**
Add support for local s3 via `s3://<host_name>:<host_port>/<bucket_name>`

Note: Must merge #1067 **before** this.

### CODE REVIEW

**Comment by CoderHam** [comment]
Yes, working on it

File: src/backends/tensorflow/graphdef_backend_factory.cc [hunk 1]
```diff
@@ -67,18 +67,29 @@ GraphDefBackendFactory::CreateBackend(
...
       GetDirectoryFiles(path, true /* skip_hidden_files */, &graphdef_files));
 
-  std::unordered_map<std::string, std::string> graphdef_paths;
+  std::unordered_map<std::string, std::string> models;
   for (const auto& filename : graphdef_files) {
     const auto graphdef_path = JoinPath({path, filename});
-    graphdef_paths.emplace(
+    std::string local_graphdef_path;
+
+    // Destory local copy if exists
```
Comment (deadeyegoodwin) [inline src/backends/tensorflow/graphdef_backend_factory.cc]: Delete this comment?

File: src/backends/tensorflow/graphdef_backend_factory.cc [hunk 2]
```diff
@@ -67,18 +67,29 @@ GraphDefBackendFactory::CreateBackend(
...
 
+  // Create the backend for the model and all the execution contexts
+  // requested for this model.
   std::unique_ptr<GraphDefBackend> local_backend(new GraphDefBackend);
   RETURN_IF_ERROR(local_backend->Init(
       path, model_config, backend_config_.get(), kTensorFlowGraphDefPlatform));
-  RETURN_IF_ERROR(local_backend->CreateExecutionContexts(graphdef_paths));
+  RETURN_IF_ERROR(local_backend->CreateExecutionContexts(models));
+
+  // Destory local copy if exists
```
Comment (deadeyegoodwin) [inline src/backends/tensorflow/graphdef_backend_factory.cc]: spelling

File: src/backends/tensorflow/savedmodel_backend_factory.cc [hunk 3]
```diff
@@ -66,19 +66,31 @@ SavedModelBackendFactory::CreateBackend(
...
   RETURN_IF_ERROR(GetDirectorySubdirs(path, &savedmodel_subdirs));
 
-  std::unordered_map<std::string, std::string> savedmodel_paths;
+  std::unordered_map<std::string, std::string> models;
   for (const auto& filename : savedmodel_subdirs) {
     const auto savedmodel_path = JoinPath({path, filename});
-    savedmodel_paths.emplace(
+    std::string local_savedmodel_path;
+
+    // Destory local copy if exists
```
Comment (deadeyegoodwin) [inline src/backends/tensorflow/savedmodel_backend_factory.cc]: Remove?

File: src/backends/tensorflow/savedmodel_backend_factory.cc [hunk 4]
```diff
@@ -66,19 +66,31 @@ SavedModelBackendFactory::CreateBackend(
...
+  // Create the backend for the model and all the execution contexts
+  // requested for this model.
   std::unique_ptr<SavedModelBackend> local_backend(new SavedModelBackend);
   RETURN_IF_ERROR(local_backend->Init(
       path, model_config, backend_config_.get(),
       kTensorFlowSavedModelPlatform));
-  RETURN_IF_ERROR(local_backend->CreateExecutionContexts(savedmodel_paths));
+  RETURN_IF_ERROR(local_backend->CreateExecutionContexts(models));
+
+  // Destory local copy if exists
```
Comment (deadeyegoodwin) [inline src/backends/tensorflow/savedmodel_backend_factory.cc]: spelling

File: src/core/filesystem.h [hunk 5]
```diff
@@ -98,6 +98,17 @@ Status GetDirectoryFiles(
 /// \return Error status
 Status ReadTextFile(const std::string& path, std::string* contents);
 
+/// Create a local copy of the file (if needed).
```
Comment (deadeyegoodwin) [inline src/core/filesystem.h]: Update this comment and one below to talk about folder, not file.

File: src/core/filesystem.cc [hunk 6]
```diff
@@ -39,9 +39,13 @@
 #include <aws/s3/model/HeadBucketRequest.h>
 #include <aws/s3/model/HeadObjectRequest.h>
 #include <aws/s3/model/ListObjectsRequest.h>
+#include <re2/re2.h>
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: re2 is included unconditionally below so not needed here

File: src/core/filesystem.cc [hunk 7]
```diff
@@ -204,6 +214,21 @@ LocalFileSystem::ReadTextFile(const std::string& path, std::string* contents)
   return Status::Success;
 }
 
+Status
+LocalFileSystem::DownloadFileFolder(
+    const std::string& path, std::string* local_path)
+{
+  *local_path = path;
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: Put a comment "For local file system we don't actually need to download the folder... just use it in place"

File: src/core/filesystem.cc [hunk 8]
```diff
@@ -510,6 +538,21 @@ GCSFileSystem::ReadTextFile(const std::string& path, std::string* contents)
   return Status::Success;
 }
 
+Status
+GCSFileSystem::DownloadFileFolder(
+    const std::string& path, std::string* local_path)
+{
+  *local_path = path;
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: Some comment here as to why we don't need to download because using TF built-in support for accessing GCS.

File: src/core/filesystem.cc [hunk 9]
```diff
@@ -555,16 +601,21 @@ S3FileSystem::ParsePath(
...
-    *bucket = path.substr(bucket_start, bucket_end - bucket_start);
-    *object = path.substr(bucket_end + 1);
-  } else {
-    *bucket = path.substr(bucket_start);
-    *object = "";
+  re2::RE2 s3_regex(
+      "s3://([a-z]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-z.-_]+)*)?)");
+  std::string host_name, host_port;
+  if (!RE2::FullMatch(path, s3_regex, &host_name, &host_port, bucket, object)) {
+    int bucket_start = path.find("s3://") + 5;
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: + strlen("s3://")
Documents better what you are doing and compiler will optimize it to constant 5.

File: src/core/filesystem.cc [hunk 10]
```diff
@@ -807,6 +881,123 @@ S3FileSystem::ReadTextFile(const std::string& path, std::string* contents)
...
+Status
+S3FileSystem::DownloadFileFolder(
+    const std::string& path, std::string* local_path)
+{
+  bool exists;
+  RETURN_IF_ERROR(FileExists(path, &exists));
+
+  if (!exists) {
+    return Status(
+        RequestStatusCode::INTERNAL, "File does not exist at " + path);
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: "Folder does not..."

File: src/core/filesystem.cc [hunk 11]
```diff
@@ -807,6 +881,123 @@ S3FileSystem::ReadTextFile(const std::string& path, std::string* contents)
...
+  }
+
+  bool is_dir = false;
+  std::set<std::string> contents, files;
+  std::string file_template = "/tmp/fileXXXXXX";
+  IsDirectory(path, &is_dir);
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: RETURN_IF_ERROR

File: src/core/filesystem.cc [hunk 12]
```diff
@@ -807,6 +881,123 @@ S3FileSystem::ReadTextFile(const std::string& path, std::string* contents)
...
+        if (!status) {
+          return Status(
+              RequestStatusCode::INTERNAL,
+              "Failed to create local temp file: " + local_file_path);
+        }
+
+        std::set<std::string> subdir_files;
+        RETURN_IF_ERROR(
+            GetDirectoryFiles(JoinPath({path, *iter}), &subdir_files));
+        // iter = contents.erase(iter);
```
Comment (deadeyegoodwin) [inline src/core/filesystem.cc]: remove commented

File: src/core/filesystem.h (hunk 5 above)
Comment (CoderHam) [reply src/core/filesystem.h]: In case of graphdef it is a file and not a folder

File: src/core/filesystem.cc (hunk 10 above)
Comment (CoderHam) [reply src/core/filesystem.cc]: Graphdef -> file, savedmodel -> folder

**Comment by deadeyegoodwin** [comment]
@CoderHam This needs to be manually rebased

**Comment by CoderHam** [comment]
Rebased and re-ran CI
